### ISSUE TITLE
More detailed description of (sample) usage needed

### ISSUE THREAD

**Issue by JuergenKosel** [Azure/iot-edge-opc-proxy#15]
Hello,

could you please describe how to start the proxyd to run the samples, or to connect the sample opc ua client to another opc ua server.
From the description it is not clear, if one instance of proxyd is needed for the opc ua server(s) and one for the sample client.
An example would be great, where the opc ua server runs on a different (virtual/physical) machine than the client.

Greetings
  Juergen

**Comment by JuergenKosel** [comment]
Hello,

please also add Hyperlinks to the related azure documentation, e.g. https://docs.microsoft.com/de-de/azure/service-bus-relay/relay-create-namespace-portal for the creation of the mentioned "Service Bus Hybrid Connection Namespace".
Otherwise the user needs to search in the online help and hope that there are not to many Topics which accidently also match the search pattern.

Greetings
Juergen

**Comment by marcschier** [comment]
Removed service bus relay support, thus closing this documentation issue.
