### ISSUE TITLE
cannot run the docker container

### ISSUE THREAD

**Issue by faister** [Azure/iot-edge-opc-proxy#34]
According to the readme, I tried docker build -t gw https://github.com/Azure/iot-gateway-proxy, but to no avail. 
PS C:\demos\iot-gateway-proxy\iot-edge> docker build -t gw https://github.com/Azure/iot-gateway-proxy
Downloading build context from remote url: https://github.com/Azure/iot-gateway-proxy 102.9 kB
Sending build context to Docker daemon   105 kB
Error response from daemon: Unknown instruction: <!DOCTYPE

Also tried the new repo name:
PS C:\demos\iot-gateway-proxy\iot-edge> docker build -t gw https://github.com/Azure/iot-edge-opc-proxy
Downloading build context from remote url: https://github.com/Azure/iot-edge-opc-proxy 102.9 kB
Sending build context to Docker daemon   105 kB
Error response from daemon: Unknown instruction: <!DOCTYPE

**Comment by marcschier** [comment]
Hi @faister, the instructions are missing a ".git" at the end of the url.  I have updated them.  Please try this with docker build -t gw https://github.com/Azure/iot-gateway-proxy.git or docker build -t gw https://github.com/Azure/iot-edge-opc-proxy.git.
