### ISSUE TITLE
Missing backward compatibility

### ISSUE THREAD

**Issue by JuergenKosel** [Azure/iot-edge-opc-proxy#41]
Hello,

the demo OPC UA client compiled from the current master (commit id dccda9da0c1b77250139e9ffa1200c3627b9d520 ) fails to connect to the proxyd counter part, if this is based on an earlier version (git tag 0.1.4-revised ).
It looks like the protocol has changed. So that communication fails, if proxyd on the server side and the application on client side are not using the same sources!

**Comment by marcschier** [comment]
That is correct.  The goal when adding browsing was to build this as service above the link layer and thus avoid backcompat breaking changes.  Unfortunately it was necessary to change the socket address and properties structures after all, which makes the link layer incompatible without additional logic.  The latter we judged as making the code too convoluted at this stage.  The goal however is that at some point in the near future we would be stable and then use a form of backwards compat logic that can deal with slight variations in serialization/deserialization protocol.  For now I bumped the link protocol version to 8 which means messages are rejected.  We should open up a conversation outside of GitHub if this affects commercialization and align project plans, but at this point (when 0.2.0 is released) it will require clients and proxies to be upgraded to the same 0.2.* version.
