### ISSUE TITLE
SSH via proxy, is FINAL_DEST the edge gateway?

### ISSUE THREAD

**Issue by ukluk** [Azure/iot-edge-opc-proxy#60]
The command to connect SSH with the final destination device uses a proxy:
ssh USER@FINAL_DEST -o "ProxyCommand=pnc %h %p"

In our example pnc = PNetCat and it has a connection string to the IoT Hub therefore it knows connected devices.

Q1) Does it support SSH to the OPC server, or it only can connect to the Edge gateway?
Q2) If this method allows to connect SSH all the way to the OPC server, how does PNetCat resolves what Edge gateway to use, assuming there are more multiple proxys connected. Does it try like the portal to iterate and "find" FINAL_DEST by sending a request to all the registered proxys? 

Q3) We saw in the device explorer that identities exist for the publisher, the proxy and the OPC servers. When trying to establish a C2E session how does it know to talk only to the "PROXYs" is there some metadata included in the cached session?

**Comment by marcschier** [comment]
Hi,

Re 1, pnetcat will tunnel (ssh) traffic through the edge proxy to the (ssh) server provided on the commandline via host port.

Re 2, correct. When no proxy guid is provided on cli it tries to autobind to a proxy that can connect to the host:port.

Re 3, tag.proxy=1 in the device twin.
