### ISSUE TITLE
IoT hub tries to connect through wrong proxyd

### ISSUE THREAD

**Issue by JuergenKosel** [Azure/iot-edge-opc-proxy#78]
Hello,

we had two devices in a test network. Each of them running one instance of proxyd, connected to the same IoT-hub.
When the the OPC UA client (of the connected factory) tried to establish a connection to one of the OPC UA servers on one of the two devices, the connection was established through the proxyd of the first device.
Now we have moved this first device into another network (e.g. "production network").
If now the OPC UA client (of the connected factory) should connect to the OPC UA endpoint of the second device, it tries to connect through the proxyd of the first device. Which could not work anymore. And it does not try to connect through the proxyd of the second device (which could work).

Unfortunately, there are no means for a user to "tell" the IoT-hub or connected factory  that such a connection establishment can not work anymore. And the IoT-hub / connected factory does not "forget" automatically a not working connection.

Greeting
Juergen

**Comment by marcschier** [comment]
Target to proxy mappings are indeed sticky.  They are there to speed up connection times.  Once a proxy is in the network, it is expected to stay there.  When moved it should be registered again with a new name or id and optionally domain.  One can delete the old proxy in the device registry for good measure.

That said, if a specified proxy, including a sticky one, cannot connect, auto discovery of alternative proxy should kick in supporting failover.  If the new proxy succeeds, the sticky target mapping is updated to reflect the new proxy.

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________
