### ISSUE TITLE
Fail to connect to OPCUA endpoint within timeout

### ISSUE THREAD

**Issue by JuergenKosel** [Azure/iot-edge-opc-proxy#80]
Hello,

during our test a huge bunch of device-ids are registered at our IoT-hub.
Some of these devices are proxyd instances, others are publishers. But the great majority of these devic-id came from OPC UA endpoint we have (tried) to connect to.

If we now want to connect through a new proxyd instance to a new OPC UA enpoint, we need several attempts to connect. It looks like the IoT-hub / connected factory needs to try to many (proxy) device-id to find the correct one to reach the new opc ua endpoint. During this attempts, some timeout may expire. So we need to try again.

**Comment by gasherma** [comment]
You need to configure the proxy instances using different domains/sites and change Connected factory to support this. This will be supported by Connected factory in an upcoming release.
