### ISSUE TITLE
Proxy refused create connections when using it as IoT edge module

### ISSUE THREAD

**Issue by ryan-ms** [Azure/iot-edge-opc-proxy#88]
Hi

I just tested the Azure Iot solution: connected factory, and publisher , proxy component.
I followed the step on the [publisher github repository](https://github.com/Azure/iot-edge-opc-publisher) and [proxy github repository](https://github.com/Azure/iot-edge-opc-proxy) deploy the publisher and proxy as Azure iot edge module.
And used Connected Factory to enable gateway and connect to OPCUA server.

So, after the iot edge start,  I tried to connect to gateway(my laptop) by filling **opc.tcp://tw-rychen-175:62222** in the Connect your own OPC UA server page on Connected Factory web app.

But I got the error from proxy logs as below..
<img width="939" alt="error" src="https://user-images.githubusercontent.com/29178018/43947398-91bb40b8-9cba-11e8-8844-cbf01d56273f.PNG">

But I had tested it successfully by using the self container, not sure why it can not work by using the component as iot edge module. 

------

My test environment as below: 

OPC Foundation Sample Server Simulator and OPC Proxy and OPC publisher as iot edge module in the same laptop.

The IP of my laptop is : 10.86.124.71
And my hostname of the laptop is: **tw-rychen-175**
In the etc/host file of my laptop, I also added the entry **tw-rychen-175:10.86.124.71**

**Comment by hansgschossmann** [comment]
Looks you are trying to connect to the OPC UA server integrated into the OPC Publisher (which is on port 62222). Not sure where you have it running, but you need to ensure that the there is a OPC UA server listening on 172.19.0.2:62222. A simple issue might be you need to export the port 62222, if OPC Publisher is running in a container as well.

**Comment by ryan-ms** [comment]
Thanks for replying.

Below are some updated===

My environment,

OS: win10
Running  Publisher and Proxy in Azure iot edge module in my laptop.
Running OPC UA sample server in the same laptop. 
Laptop's hostname and IP  :  tw-rychen-175:10.86.124.91

![image](https://user-images.githubusercontent.com/29178018/47776827-3dced780-dd2e-11e8-8891-d62b6528bd72.png)

Now I can successfully connect to `opc.tcp://publisher:62222`
But when I want to connect to my opc ua server on `opc.tcp://tw-rychen-175:51210/UA/SampleServer ` from connected factory.
![image](https://user-images.githubusercontent.com/29178018/47776872-5b03a600-dd2e-11e8-9397-4e0f8c95b3d6.png)


It still show the error message below.
![image](https://user-images.githubusercontent.com/29178018/47776792-2e4f8e80-dd2e-11e8-86f8-ffc4af65b7b6.png)


But When I change the url to `opc.tcp://10.86.124.91:51210/UA/SampleServer`. (use IP instead of hostname)
It can successfully connect to my opc ua server.

![image](https://user-images.githubusercontent.com/29178018/47776914-7969a180-dd2e-11e8-8755-5fb4f22818ca.png)


So in the error message

> tw-rychen-175:51210 -> 172.19.0.2:51210

it seems that the host name mapping to IP `172.19.0.2`
But my IP is `10.86.124.91`. Not sure why it map to the wrong IP.
But if I run the publisher and proxy by docker container directly instead of running as iot edge module. it works fine.

Could you kindly gives me some suggestion?

**Comment by asgaralim** [comment]
As said in connected factory architecture. I created azure iot edge system on linux system. I deployed OPC publisher and OPC proxy containers on to edge systeam. Could you please provide details how to configure opc proxy container  and opc ua client App ( in cloud), so that opc ua client application send command to opc ua server using opc proxy.  How to implement and configure these components
