### ISSUE TITLE
Support Windows containers

### ISSUE THREAD

**Issue by Strandfelt** [Azure/iot-edge-opc-proxy#90]
As of December 2018 (MicrosoftDocs/azure-docs@9588590cfd21bedf0a8c9b9bcb483b3f95da8236), IoT Edge for Windows only supports Linux containers for development purposes. 
However, this project has not been created with a Dockerfile that supports Windows containers and trying to pull latest release 1.0.4 on a host running with Windows Containers will result in an error.

**Comment by marcschier** [comment]
We will not support windows containers for proxy, but we have support for all architectures in https://github.com/Azure/azure-iiot-opc-twin-module, which is the successor to opc proxy in its capabilities.
